# Dockerfile.server
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
# Install runtime dependencies
RUN apt-get update && \
    apt-get install -y libopencv-dev libssl-dev libcpprest-dev && \
    apt-get clean

# Set working directory
WORKDIR /app

# Copy the compiled binary from the builder container
COPY --from=builder /app/build/ConvNetServer /app/

COPY ../data /app/data/

RUN chmod +x /app/ConvNetServer

# Run the server
# CMD ["sleep", "3600"]
