# Dockerfile.web
FROM python:3.8

# Set working directory
WORKDIR /app

# Copy the HTML file to the container
COPY ../index.html /app/

# Run a simple HTTP server to serve index.html
CMD ["python3", "-m", "http.server", "80"]
